const StringsOfMarathi = {
    thisLanguage : 'मराठी',
    language : 'भाषा',
    selectLanguage : 'भाषा निवडा',
    appName: 'फंडू नोट्स',
    welcome: 'स्वागत आहे',
    signInMessage: 'सुरू ठेवण्यासाठी साइन इन करा!',
    email: 'ईमेल',
    password: 'पासवर्ड',
    confirmPassword: 'पासवर्डची पुष्टी करा',
    showPassword: 'पासवर्ड दाखवा',
    forgotPassword: 'पासवर्ड विसरलात?',
    signIn: 'साइन इन करा',
    signUp: 'साइन अप करा',
    signOut: 'साइन आउट',
    signInTag: 'साइन इन करा',
    signUpTag: 'साइन अप करा',
    or: 'किंवा',
    connectFacebook: 'फेसबुकसह कनेक्ट करा',
    connectGoogle: 'गूगल सह कनेक्ट करा',
    newUser: "मी एक नवीन वापरकर्ता आहे,",
    createAccount: 'खाते तयार करा,',
    signUpMessage: 'प्रारंभ करण्यासाठी साइन अप करा!',
    firstName: 'पहिले नाव',
    lastName: 'आडनाव',
    selectDOB: 'जन्मतारीख निवडा :',
    dashboard: 'डॅशबोर्ड',
    searchNote: 'नोट्स शोधा',
    archive: 'संग्रह',
    deleted: 'हटविले',
    title: 'शीर्षक',
    note: 'टीप',
    delete: 'हटवा',
    makeCopy: 'प्रत बनव',
    send: 'पाठवा',
    collaborator: 'सहयोगी',
    labels: 'लेबल',
    takePhoto: 'फोटो घ्या',
    addImage: 'प्रतिमा जोडा',
    drawing: 'रेखांकन',
    recording: 'रेकॉर्डिंग',
    tickBoxes: 'चेक बॉक्स',
    forgotYourPassword : 'आपण पासवर्ड विसरलात,',
    dontWorry : "काळजी करू नका!",
    forgotPasswordDescription : 'आपला ईमेल प्रविष्ट करा आणि आपल्या ईमेलवर संकेतशब्द रीसेट करण्याच्या सूचना प्राप्त करण्यासाठी रीसेटवर क्लिक करा',
    reset : 'रीसेट करा',
    alreadyHaveAccount : 'माझ्याकडे आधीच खाते आहे,',
    restore : 'पुनर्संचयित करा',
    deleteforever : 'कायमचे हटवा',

}

export default StringsOfMarathi;