const StringsOfEnglish = {
    thisLanguage : 'English',
    language : 'Languages',
    selectLanguage : 'Select Language',
    appName : 'Fundoo Notes',
    welcome : 'Welcome,',
    signInMessage : 'Sign in to continue!',
    email : 'Email',
    password : 'Password',
    confirmPassword : 'Confirm Password',
    showPassword : 'Show Password',
    forgotPassword : 'Forgot Password?',
    signIn : 'SIGN IN',
    signUp : 'SIGN UP',
    signOut : 'SIGN OUT',
    signInTag : ' Sign In',
    signUpTag : ' Sign Up',
    or : 'or',
    connectFacebook : 'CONNECT WITH FACEBOOK',
    connectGoogle : 'CONNECT WITH GOOGLE',
    newUser : "I'm a new user,",
    createAccount : 'Create Account,',
    signUpMessage : 'Sign up to get started!',
    firstName :'Firstname',
    lastName : 'Lastname',
    selectDOB : 'Select Date of birth :',
    dashboard : 'Dashboard',
    searchNote : 'Search Notes',
    archive : 'Archive',
    deleted : 'Deleted',
    title : 'Title',
    note : 'Note',
    delete : 'DELETE',
    makeCopy : 'Make A COPY',
    send : 'SEND',
    collaborator : 'COLLABORATOR',
    labels : 'LABELS',
    takePhoto : 'TAKE PHOTO',
    addImage : 'ADD IMAGE',
    drawing : 'DRAWING',
    recording : 'RECORDING',
    tickBoxes : 'TICK BOXES',
    forgotYourPassword : 'Forgot your password,',
    dontWorry : "Don't worry!",
    forgotPasswordDescription : 'Enter your email and click on reset to get password reset instructions on your email',
    reset : 'RESET',
    alreadyHaveAccount : 'I already have account,',
    restore : 'Restore',
    deleteforever : 'Delete forever',
}

export default StringsOfEnglish;