const StringsOfHindi = {
    thisLanguage : 'हिंदी',
    language : 'भाषा',
    selectLanguage : 'भाषा चुनें',
    appName : 'फंडू नोट्स',
    welcome : 'स्वागत हे,',
    signInMessage : 'जारी रखने के लिए साइन इन करें!',
    email : 'ईमेल',
    password : 'पासवर्ड',
    confirmPassword : 'पासवर्ड की पुष्टि कीजिये',
    showPassword : 'पासवर्ड दिखाओ',
    forgotPassword : 'पासवर्ड भूल गए?',
    signIn : 'साइन इन करें',
    signUp : 'साइन अप करें',
    signOut : 'प्रस्थान करें',
    signInTag : ' साइन इन करें',
    signUpTag : ' साइन अप करें',
    or : 'और',
    connectFacebook : 'फेस्बूक से जुडिये',
    connectGoogle : 'गूगल से जुडिये',
    newUser : "मैं एक नया उपयोगकर्ता हूँ,",
    createAccount : 'खाता बनाएं,',
    signUpMessage : 'शुरू करने के लिए साइन अप करें!',
    firstName :'पहला नाम',
    lastName : 'अंतिम नाम',
    selectDOB : 'जन्म तिथि चुनें :',
    dashboard : 'डैशबोर्ड',
    searchNote : 'नोट्स खोजें',
    archive : 'पुरालेख',
    deleted : 'हटाए गए',
    title : 'शीर्षक',
    note : 'टिप्पणी',
    delete : 'हटाएँ',
    makeCopy : 'एक प्रति बनाओ',
    send : 'भेजें',
    collaborator : 'सहयोगी',
    labels : 'लेबल',
    takePhoto : 'फोटो लो',
    addImage : 'फोटो जोड़ें',
    drawing : 'चित्रकला',
    recording : 'रिकॉर्ड करे',
    tickBoxes : 'टिक बॉक्स',
    forgotYourPassword: 'क्या आप पासवर्ड भूल गए,',
    dontWorry : 'चिंता मत करो!',
    forgotPasswordDescription : 'अपना ईमेल दर्ज करें और अपने ईमेल पर पासवर्ड रीसेट निर्देश प्राप्त करने के लिए रीसेट पर क्लिक करें',
    reset : 'रीसेट',
    alreadyHaveAccount : 'मेरे पास पहले से ही खाता है,',
    restore : 'लौटाना',
    deleteforever : 'हमेशा के लिए हटाएं'

}

export default StringsOfHindi;